<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Nncase.Modules.K230</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>netcoreapp7.0</TargetFramework>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>11.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="Nncase.Core">
      <HintPath>../../../env/lib/nncase/Nncase.Core.dll</HintPath>
    </Reference>
    <Reference Include="DryIoc">
      <HintPath>../../../env/lib/nncase/DryIoc.dll</HintPath>
    </Reference>
    <Reference Include="System.Reactive">
      <HintPath>../../../env/lib/nncase/System.Reactive.dll</HintPath>
    </Reference>
    <Reference Include="NetFabric.Hyperlinq">
      <HintPath>../../../env/lib/nncase/NetFabric.Hyperlinq.dll</HintPath>
    </Reference>
    <Reference Include="NetFabric.Hyperlinq.Abstractions">
      <HintPath>../../../env/lib/nncase/NetFabric.Hyperlinq.Abstractions.dll</HintPath>
    </Reference>
    <Reference Include="Nncase.Passes">
      <HintPath>../../../env/lib/nncase/Nncase.Passes.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.Extensions.Logging.Abstractions">
      <HintPath>../../../env/lib/nncase/Microsoft.Extensions.Logging.Abstractions.dll</HintPath>
    </Reference>
    <Reference Include="Nncase.CodeGen">
      <HintPath>../../../env/lib/nncase/Nncase.CodeGen.dll</HintPath>
    </Reference>
    <Reference Include="Nncase.Quantization">
      <HintPath>../../../env/lib/nncase/Nncase.Quantization.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.Extensions.Configuration.Abstractions">
      <HintPath>../../../env/lib/nncase/Microsoft.Extensions.Configuration.Abstractions.dll</HintPath>
    </Reference>
    <Reference Include="System.CommandLine">
      <HintPath>../../../env/lib/nncase/System.CommandLine.dll</HintPath>
    </Reference>
    <Reference Include="Nncase.EGraph">
      <HintPath>../../../env/lib/nncase/Nncase.EGraph.dll</HintPath>
    </Reference>
    <Reference Include="Nncase.IO">
      <HintPath>../../../env/lib/nncase/Nncase.IO.dll</HintPath>
    </Reference>
    <Reference Include="OrtKISharp">
      <HintPath>../../../env/lib/nncase/OrtKISharp.dll</HintPath>
    </Reference>
    <Reference Include="Nncase.Evaluator">
      <HintPath>../../../env/lib/nncase/Nncase.Evaluator.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.Extensions.DependencyInjection.Abstractions">
      <HintPath>../../../env/lib/nncase/Microsoft.Extensions.DependencyInjection.Abstractions.dll</HintPath>
    </Reference>
    <Reference Include="Nncase.Modules.StackVM">
      <HintPath>../../../env/lib/nncase/Nncase.Modules.StackVM.dll</HintPath>
    </Reference>
    <Reference Include="System.Linq.Async">
      <HintPath>../../../env/lib/nncase/System.Linq.Async.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>